// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Attack struct {
	Name   string `json:"name"`
	Type   string `json:"type"`
	Damage int    `json:"damage"`
}

type Pokemon struct {
	ID                    string                       `json:"id"`
	Number                int                          `json:"number"`
	Name                  string                       `json:"name"`
	Weight                *PokemonDimension            `json:"weight"`
	Height                *PokemonDimension            `json:"height"`
	Classification        string                       `json:"classification"`
	Types                 []string                     `json:"types"`
	Resistant             []string                     `json:"resistant"`
	Attacks               *PokemonAttack               `json:"attacks"`
	Weaknesses            []string                     `json:"weaknesses"`
	FleeRate              float64                      `json:"fleeRate"`
	MaxCp                 int                          `json:"maxCP"`
	Evolutions            []*Pokemon                   `json:"evolutions"`
	EvolutionRequirements *PokemonEvolutionRequirement `json:"evolutionRequirements"`
	MaxHp                 int                          `json:"maxHP"`
	Image                 string                       `json:"image"`
	Sound                 string                       `json:"sound"`
	IsFavorite            bool                         `json:"isFavorite"`
	CommonCaptureArea     *string                      `json:"CommonCaptureArea"`
	Asia                  *string                      `json:"Asia"`
	AustraliaNewZealand   *string                      `json:"AustraliaNewZealand"`
	WesternEurope         *string                      `json:"WesternEurope"`
	NorthAmerica          *string                      `json:"NorthAmerica"`
	PokMonClass           *string                      `json:"PokMonClass"`
	Legendary             *string                      `json:"LEGENDARY"`
	Mythic                *string                      `json:"MYTHIC"`
}

type PokemonAttack struct {
	Fast    []*Attack `json:"fast"`
	Special []*Attack `json:"special"`
}

type PokemonConnection struct {
	Limit  int        `json:"limit"`
	Offset string     `json:"offset"`
	Count  int        `json:"count"`
	Edges  []*Pokemon `json:"edges"`
}

type PokemonDimension struct {
	Minimum string `json:"minimum"`
	Maximum string `json:"maximum"`
}

type PokemonEvolutionRequirement struct {
	Amount int    `json:"amount"`
	Name   string `json:"name"`
}

type PokemonFilterInput struct {
	SearchType *string `json:"searchType"`
	SearchName *string `json:"searchName"`
	IsFavorite *bool   `json:"isFavorite"`
}

type PokemonsQueryInput struct {
	Limit  *int                `json:"limit"`
	Offset *string             `json:"offset"`
	Filter *PokemonFilterInput `json:"filter"`
}
